version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=Host(`dishdash.ru`) && PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=${NGINX_PORT}"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.routers.frontend.entrypoints=https"
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
    external: true